#!/usr/bin/env bash
# Dispaly subdomain information

list_domain () {
	ip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $ip" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ -z $2 ]
then
	list_domain "$1" "www"
	list_domain "$1" "lb-01"
	list_domain "$1" "web-01"
	list_domain "$1" "web-02"
else

	list_domain "$1" "$2"
fi
