#!/usr/bin/env bash
# Configuration of the HAProxy

global
        log /dev/log local0
        maxconn 2000
        user haproxy
        group haproxy
	tune.ssl.default-dh-param 2048


defaults
        log global
        mode http
        option httplog
        option dontlognull
        retries 3
        option redispatch
        timeout connect 5000
        timeout client 10000
        timeout server 10000

frontend http-page
	mode http
	bind *:80
	bind *:433 ssl crt /etc/ssl/certs/www.bdnb.site.pem
	redirect scheme https code 301 if !{ ssl_fc }
	default_backend http_servers

