#!/usr/bin/env bash
# Install nginx on web-01 server

apt-get update
apt-get install -y nginx

mkdir -p /etc/nginx/www/html
touch /etc/nginx/www/html/index.html

printf %s "
	server {
		listen 80 default_server;
		listen [::]:80 default_server;

		root /etc/nginx/www/html;
		index index.html index.htm;
}
" > /etc/nginx/sites-available/default
service nginx restart
