#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed
#+ archive out of it
# date +"%d-%m-20%y"

sudo mysqldump -u root -p $1 * > backup.sql
tar -cvzf $(date +%d-%m-20%y).tar.gz backup.sql
