#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# with a sleep 2 in between each iteration
# "I am invincible!!!" when receiving a STGTERM signal

printout()
{
	echo "I am invincible!!!"
}

while [ $# ]
do
	trap printout SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
