#!/usr/bin/env bash
# displays the time of 12 hours and 59 minutes.

hourse=0
min=1

while [ $hourse -le 12 ]; do
	
        echo "Hour: $hourse"
	min=1
        while [ $min -le 59 ]; do
                echo  "$min"
                min=$((min + 1))
        done
        hourse=$((hourse + 1))
done
