#!/usr/bin/env bash
# display:
##	The content of the current directory
##	In a list format
##	Where only the part of the name after the first dash is displayed

LIST=`ls | cut -d "-" -f 2`

for i in $LIST
do
	echo "$i"
done
