#!/usr/bin/env bash
# Conifg Firewall
#+ and allow 22, 443, 80 prots connections

apt-get upgrade ufw

sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
