#!/usr/bin/env bash
# Configure Nginx to serve page from the route /airbnb-onepage/

printf %s "server{
        listen          80 default_server;
        listen          [::]:80 default_server;
        root            /var/www/html;
        index           index.html index.htm;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location /hbnb_static {
                alias /data/web_static/current;
                index index.html index.htm;
        }

        error_page 404 /404.html;
        location /404 {
                root /etc/nginx/html;
                internal;
        }

        location /airbnb-onepage/ {
                include proxy_params;
                proxy_pass http://0.0.0.0:5000/airbnb-onepage;
        }

        add_header X-Served-By ${HOST};
}" > /etc/nginx/sites-available/default

sudo service nginx restart
